#https://marketplace.visualstudio.com/items?itemName=humao.rest-client
#curl -v http://localhost:8080/api/accounts

###
GET http://localhost:8080/api/accounts HTTP/1.1

###
GET http://localhost:8080/api/accounts/11 HTTP/1.1

###
POST http://localhost:8080/api/user HTTP/1.1
content-type: application/json

{
    "firstName": "Sultan",
    "lastName": "Moumeneen"
}

###
PUT  http://localhost:8080/api/user/4 HTTP/1.1
content-type: application/json

{
    "firstName": "tiok",
    "lastName": "tuk"
}

###
DELETE   http://localhost:8080/api/user/8 HTTP/1.1
content-type: application/json