#https://marketplace.visualstudio.com/items?itemName=humao.rest-client
#curl -v http://localhost:8080/api/accounts

###
GET http://localhost:8080/api/accounts HTTP/1.1

###
GET http://localhost:8080/api/accounts/5 HTTP/1.1

###
POST http://localhost:8080/api/accounts HTTP/1.1
content-type: application/json

{
    "accountNumber": "4152637890",
    "balance": 1400
}

###
PUT  http://localhost:8080/api/accounts HTTP/1.1
content-type: application/json

{
    "id" : 1,
    "accountNumber" : "1234567893535",
    "balance" : "12"
}

###
DELETE   http://localhost:8080/api/accounts/5 HTTP/1.1

###
PATCH   http://localhost:8080/api/accounts/5/deposit HTTP/1.1
content-type: application/json

{
    "amount" : "500"
}

###
PATCH   http://localhost:8080/api/accounts/2/withdraw HTTP/1.1
content-type: application/json

{
    "amount" : "100"
}